# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f2241fa3048a3d90387466ae93a09a5389599c536cb42d1b07a66edda6aca04a9e16e0e8189b6b402ff15ba5ae4551f8aba3c826528755a5d3e5985de8b973

test:
  secret_key_base: f250f92249598bc0838a90d70b118e641ae185c84a0dc259a88ff1585726264013cc58bab02c349cb4582d5c972b5966ca8888e0ca428024b92b4bd9d36834aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
